### ISSUE TITLE
Creating attestation for zip in releases

### ISSUE THREAD

**Issue by soderlind** [johnbillion/attest-wordpress-plugin-build-provenance#14]
Do you see any reason why this isn't working?:

```yml
name: Manually Build Release Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        type: string
      zip:
        description: 'Output zip filename (e.g. my-plugin.zip)'
        required: true
        type: string

jobs:
  create-release:
    name: Create Release Package
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build plugin # Remove or modify this step as needed
        run: |
          composer install --no-dev

      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ${{ github.event.inputs.zip }}
          exclusions: '*.git* .editorconfig composer* *.md vendor/*/test* vendor/*/docs'

      - name: Upload to release
        id: upload
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.event.inputs.zip }}
          tag_name: ${{ github.event.inputs.tag }}

      - name: Generate attestation
        uses: johnbillion/action-wordpress-plugin-attestation@0.7.0
        with:
          zip-url: ${{ fromJson(steps.upload.outputs.assets)[0].browser_download_url }}
```

**Comment by szepeviktor** [comment]
What is your error message?

**Comment by szepeviktor** [comment]
`zip-path` seems to be mandatory.

https://github.com/johnbillion/action-wordpress-plugin-attestation/blob/260e74afa5d1ecbc57b4bb67e390159026b58d45/action.yml#L9-L12

Try `zip-url: ${{ github.event.inputs.zip }}`

**Comment by soderlind** [comment]
I'm not getting an error, but it stops on creating the attestation:

```txt
Run johnbillion/action-wordpress-plugin-attestation@0.7.0
Run zipurl="$ZIP_URL"
Fetching plugin ZIP from https://github.com/soderlind/zip-test/releases/download/1.0.0/abc11.zip ...
Plugin ZIP not available yet (HTTP status 404), retrying in 20 seconds...
Plugin ZIP not available yet (HTTP status 404), retrying in 20 seconds...
Plugin ZIP not available yet (HTTP status 404), retrying in 20 seconds...
Plugin ZIP not available yet (HTTP status 404), retrying in 20 seconds...
```

**Comment by soderlind** [comment]
btw, made the repo public

**Comment by szepeviktor** [comment]
> Try `zip-url: ${{ github.event.inputs.zip }}`

No! Try `zip-path: ${{ github.event.inputs.zip }}`
Sorry.

**Comment by soderlind** [comment]
Nah.. when I use `zip_path`, it tries to get the plugin from  https://downloads.wordpress.org/plugin/zip-test.main.zip

As per [the documentation](https://github.com/johnbillion/action-wordpress-plugin-attestation?tab=readme-ov-file#does-this-work-for-hosts-other-than-wordpressorg), I should use `zip_url`:

**Comment by szepeviktor** [comment]
Sent a PR ...

**Comment by soderlind** [comment]
If you look at the workflow run at https://github.com/soderlind/zip-test/actions/runs/12819130119/job/35746152419, you'll see that the url to the zip is correct and that the zip exist.

btw, I also tried to do this in two separate jobs, the first created the release, the seconnd tried to create the attestation.

**Comment by szepeviktor** [comment]
You need both. Please see the PR.

**Comment by soderlind** [comment]
Merged, and running now: https://github.com/soderlind/zip-test/actions/runs/12819516574/job/35747313133

**Comment by szepeviktor** [comment]
🚀

GitHub redirects to a signed URL: `objects.githubusercontent.com`

This attestation action needs a HTTP/200 response code.
https://github.com/johnbillion/action-wordpress-plugin-attestation/blob/260e74afa5d1ecbc57b4bb67e390159026b58d45/action.yml#L81
That is a problem.

**Comment by soderlind** [comment]
Yep, I see that. Ok, back to the GitHub doc :)

**Comment by soderlind** [comment]
Also when using the GitHub API, you'll get an URL like the one I got (`asstets.browser_download_url`), which is a 302 to the correct URL. 

The easy fix is to allow 302 in https://github.com/johnbillion/action-wordpress-plugin-attestation/blob/260e74afa5d1ecbc57b4bb67e390159026b58d45/action.yml#L81

**Comment by soderlind** [comment]
Thank you @szepeviktor, your latest PR fixed this :)

https://github.com/soderlind/zip-test/attestations/4475034

**Comment by soderlind** [comment]
For you, who wonder, this is the working GitHub Action:

```yml
name: Manually Build Release Zip

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        type: string
      zip:
        description: 'Output zip filename (e.g. my-plugin.zip)'
        required: true
        type: string

jobs:
  create-release:
    name: Create Release Package
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build plugin # Remove or modify this step as needed
        run: |
          composer install --no-dev

      - name: Create zip archive
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: ${{ github.event.inputs.zip }}
          exclusions: '*.git* .editorconfig composer* *.md vendor/*/test* vendor/*/docs'

      - name: Upload to release
        id: upload
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.event.inputs.zip }}
          tag_name: ${{ github.event.inputs.tag }}

      - name: Get final asset URL
        id: asset_url
        run: |
          URL="$(curl -s -I -o /dev/null -w "%{redirect_url}" "${{ fromJson(steps.upload.outputs.assets)[0].browser_download_url }}")"
          echo "final_url=${URL}" >> "${GITHUB_OUTPUT}"

      - name: Generate attestation
        uses: johnbillion/action-wordpress-plugin-attestation@0.7.0
        with:
          zip-path: ${{ github.event.inputs.zip }}
          zip-url: ${{ steps.asset_url.outputs.final_url }}

```
